"""Initial migration with Character and Event models

Revision ID: 7d69bb6c31b0
Revises:
Create Date: 2025-05-03 15:38:46.447739

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7d69bb6c31b0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "character",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("family_name", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=50), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("birth_place", sa.String(length=150), nullable=True),
        sa.Column("mother_id", sa.UUID(), nullable=True),
        sa.Column("father_id", sa.UUID(), nullable=True),
        sa.Column(
            "gender",
            sa.Enum("MALE", "FEMALE", "INTERSEX", "OTHER", name="gender"),
            nullable=True,
        ),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("weight", sa.Integer(), nullable=True),
        sa.Column(
            "blood_type",
            sa.Enum(
                "A_POS",
                "A_NEG",
                "B_POS",
                "B_NEG",
                "O_POS",
                "O_NEG",
                "AB_POS",
                "AB_NEG",
                name="bloodtype",
            ),
            nullable=True,
        ),
        sa.Column(
            "eye_color",
            sa.Enum(
                "LIGHT_BLUE",
                "BLUE",
                "GREEN",
                "HAZEL",
                "BROWN",
                "BLACK",
                "RED",
                "YELLOW",
                "ORANGE",
                "PINK",
                "PURPLE",
                "GRAY",
                name="eyecolor",
            ),
            nullable=True,
        ),
        sa.Column("hair_color", sa.String(length=50), nullable=True),
        sa.Column(
            "race",
            sa.Enum(
                "INUIT",
                "NATIVE_AMERICAN",
                "CENTRAL_AMERICAN",
                "SOUTH_AMERICAN",
                "PACIFIC_ISLANDER",
                "NORTHERN_EUROPEAN",
                "SOUTH_EUROPEAN",
                "EASTERN_EUROPEAN",
                "MIDDLE_EASTERN",
                "INDIAN",
                "SOUTH_EAST_ASIAN",
                "NORTH_AFRICAN",
                "AFRICAN",
                name="race",
            ),
            nullable=True,
        ),
        sa.Column(
            "build",
            sa.Enum("SLIM", "ATHLETIC", "AVERAGE", "SOFT", "FAT", name="build"),
            nullable=True,
        ),
        sa.Column("strength", sa.Integer(), nullable=True),
        sa.Column("endurance", sa.Integer(), nullable=True),
        sa.Column("dexterity", sa.Integer(), nullable=True),
        sa.Column("constitution", sa.Integer(), nullable=True),
        sa.Column("intelligence", sa.Integer(), nullable=True),
        sa.Column("wisdom", sa.Integer(), nullable=True),
        sa.Column("charisma", sa.Integer(), nullable=True),
        sa.Column("traits", sa.JSON(), nullable=True),
        sa.Column("hobbies", sa.JSON(), nullable=True),
        sa.Column("occupation", sa.String(length=100), nullable=True),
        sa.Column("primary_address", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["father_id"],
            ["character.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mother_id"],
            ["character.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "character_siblings",
        sa.Column("character_id", sa.UUID(), nullable=False),
        sa.Column("sibling_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["character.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sibling_id"],
            ["character.id"],
        ),
        sa.PrimaryKeyConstraint("character_id", "sibling_id"),
    )
    op.create_table(
        "event_characters",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["character.id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["event.id"],
        ),
        sa.PrimaryKeyConstraint("event_id", "character_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event_characters")
    op.drop_table("character_siblings")
    op.drop_table("event")
    op.drop_table("character")
    # ### end Alembic commands ###
